server:
  port: 8080
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://node-01:3306/estore?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
eureka:
  client:
    service-url:
      # 指定注册中心的地址
      defaultZone: http://node-02:8761/eureka/
mybatis:
  type-aliases-package: com.briup.estore.common.bean
  mapper-locations: classpath:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"