server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: node-02
spring:
  application:
    name: register-center
management:
  endpoints:
    web:
      exposure:
        include: "*"
