server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://node-01:3306/estore?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
eureka:
  client:
    service-url:
      # 指定注册中心的地址
      defaultZone: http://node-02:8761/eureka/
mybatis:
  type-aliases-package: com.briup.estore.common.bean
  mapper-locations: classpath:mapper/*.xml
#分页信息
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

#支付宝沙箱配置信息
alipay:
  server-url: 
  private-key: 
  alipay-public-key: 
  format: json
  charset: utf-8
  sign-type: RSA2
  app-id: 2016091900545865
  notify-url: http://estore.com/order
  return-url: http://estore.com/user/order.html