server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://node-01:3306/estore?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
eureka:
  client:
    service-url:
      # 指定注册中心的地址
      defaultZone: http://node-02:8761/eureka/
mybatis:
  type-aliases-package: com.briup.estore.common.bean
  mapper-locations: classpath:mapper/*.xml
#分页信息
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

#支付宝沙箱配置信息
alipay:
  server-url: https://openapi.alipaydev.com/gateway.do
  private-key: #这里写私钥
  alipay-public-key: #这里写阿里公钥
  format: json
  charset: utf-8
  sign-type: RSA2
  app-id: #这里写APP_ID
  #异步通知地址
  notify-url: http://127.0.0.1/order
  #返回地址
  return-url: http://127.0.0.1/user/order.html