server:
  port: 9001
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/estore?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  type-aliases-package: com.briup.estore.common.bean
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      # 指定注册中心的地址
      defaultZone: http://localhost:8761/eureka/
#分页信息
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true